theme: jekyll-theme-slate
title: Marcus Marosvari's homepage
description: Marcus' github website!

I study Computer Science at Boise State University. Thus far I have completed or am currently enrolled in the following courses:
- CS121: Computer Science I
- CS221: Computer Science II
- CS253: Introduction to Systems Programming
- CS-HU153: Navigating Computer Systems
- CS-HU250: Introduciton to Version Control
